#!/bin/bash

echo -n "Sisesta suvaline täisarv:"
read arv
if (($arv % 2 == 0)) #kui arv jagub täpselt kahega (st. on paarisarv), on jääk 0
then echo "Antud arv on paaris."
else echo "Antud arv on paaritu."
fi
