#!/bin/bash

echo "Reisijate arv grupis: "
read reisijad
echo "Kohtade arv bussis: "
read kohti

taidetud=$(($reisijad / $kohti))
if (($reisijad % $kohti > 0))
then taidetud=$(($taidetud + 1))
else :
fi
#maha=`expr $reisijad - $taidetud \* $kohti`
#echo "Täidetud busse on $taidetud. Maha jääb $maha inimest."
echo "Kokku on vaja $taidetud bussi."
