#!/bin/bash
if [ $# -ne 1 ]
then echo "Kasutamise seletus:"
	echo "$0 täisarv"
else
	if [ $(($1 % 2)) -eq 0 ] #kui arv jagub täpselt kahega (st. on paarisarv), on jääk 0
	then echo "Antud arv on paaris."
	else echo "Antud arv on paaritu."
	fi
fi
