#!/bin/bash

echo -n "Sisesta suvaline täisarv:"
read numbrid

if [ $numbrid -lt 0 ]; then
	numbrid=$(($numbrid * -1))
fi
summa=0
while [ $numbrid -gt 0 ]
do
	arv=$(($numbrid % 10))
	numbrid=$(($numbrid / 10))
	summa=$(($summa + $arv))
done
echo "Summa on $summa"
