#!/bin/bash

echo -n "Sisesta a külje väärtus: "
read a
echo -n "Sisesta b külje väärtus: "
read b
echo -n "Sisesta c külje väärtus: "
read c
p=`echo "scale=2; ($a+$b+$c) /2" | bc -l`
pindala=`echo "scale=2; sqrt($p*($p-$a)*($p-$b)*($p-$c))" | bc -l`
echo "Kolmnurga pindala on: "
echo $pindala 
