#! /bin/bash
#
# kasutaja tervitus
#
echo -n "Tere  "
echo -n `who am i | cut -c1 | tr [:lower:] [:upper:]` # lõika esimene täht ja muuda suureks
echo -n `who am i | cut -c2-` # lõika tähed alates 2st
echo "!"
#
# skripti lõpp
