#!/bin/bash
#
# kasutajate nimekiri kujul Perenimi, Eesnimi
#
# skripti algus
#
who | cut -f1 -d" " | cut -f2 -d"." > perenimi # lõikame perenime, lisame faili
who | cut -f1 -d" " | cut -f1 -d"." > eesnimi # lõikame eesnime. lisame faili
paste -d"." perenimi eesnimi > nimed # kleebime failid õiges järjekorras kokku
awk {print} nimed | sort # sorteerime väljundit ja võtame korduvad välja
#
# skripti lõpp
